---
- type: remove
  path: /instance_groups/name=diego-cell/vm_extensions

- type: replace
  path: /instance_groups/name=diego-cell/azs/-
  value: z3

- type: replace
  path: /instance_groups/name=diego-cell/instances
  value: ((cell_instances))

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs2-rootfs-setup/properties/cflinuxfs2-rootfs/trusted_certs
  value: ((aws_rds_combined_ca_bundle))

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden?/log_level
  value: error

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/debug_listen_address

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/destroy_containers_on_start

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/containers/trusted_ca_certificates

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/containers/proxy?/enabled?
  value: true

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=rep/properties/diego?/executor/memory_capacity_mb
  value: ((cell_memory_capacity_mb))

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/tcp

- type: remove
  path: /instance_groups/name=diego-cell/jobs/name=route_emitter/properties/uaa

- type: replace
  path: /instance_groups/name=diego-cell/networks/0/name
  value: cell
